site_url: https://makerwiki.netlify.app/
logo_url: https://makerwiki.netlify.app/icon.png

publish_mode: editorial_workflow
backend:
  name: git-gateway
  branch: main
  repo: thk-code-arch/makerwiki
local_backend: true
media_folder: static/img
public_folder: /img

# Docs: https://www.netlifycms.org/docs/configuration-options/#collections
collections:
  - name: 'material'
    label: 'Material'
    # identifier_field: name
    folder: 'assets/content/material'
    create: true
    format: 'json'
    slug: "{{year}}-{{month}}-{{day}}_{{fields.kategorisierung}}-{{title}}"
    # editor:
    #   preview: true

    fields:
      - label: 'Title'
        name: 'title'
        title: ''
      - label: 'Material Image'
        name: 'image'
        widget: 'image'
      - label: "Kategorisierung"
        name: "kategorisierung"
        widget: "object"
        summary: '{{fields.name}}: {{fields.kategorisierung}}'
        fields:
          - label: "Gruppe"
            name: "gruppe"
            widget: "select"
            options:
            - { label: "Holz", value: "Holz" }
          - label: "Untergruppe"
            name: "untergruppe"
            widget: "select"
            options:
            - { label: "Laubholz", value: "Laubholz" }
          - label: "Art"
            name: "art"
            widget: "select"
            options:
            - { label: "Eiche", value: "Eiche" }
      - label: "Mechanische Eigenschaften"
        name: "mechanische eigenschaften"
        widget: "object"
        summary: '{{fields.name}}: {{fields.mechanische}}'
        fields:
        - label: 'Dichte'
          name: 'dichte'
          widget: 'object'
          fields:
            - label: 'Dichte'
              name: 'dichte'
              widget: 'object'
              fields:
              - { widget: "number", label: 'min', name: 'min', value_type: 'int'}
              - { widget: "number", label: 'max', name: 'max', value_type: 'int'}

            - label: "Einheit"
              name: "einheit"
              widget: "select"
              options:
              - { label: "Kilogramm per m2", value: "kgm3" }
          
            
    # Process
  - name: 'process'
    label: 'Process'
    label_singular: 'process'
    folder: 'assets/content/process'
    create: true
    format: 'json'
    slug: '{{slug}}'
    preview_path: 'process/{{slug}}'
    fields:
      - { label: 'Process name', name: 'name', widget: 'string' }
      - { label: 'Alternative name', name: 'altName', widget: 'string' }
      - { label: 'Short Description', name: 'shortDescription', widget: 'string' }
      - { label: 'MD Description', name: 'mdDescription', widget: 'markdown' }
      - {
          label: 'Process Image',
          name: 'image',
          widget: 'string',
          required: false
        }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - label: "Maße"
        name: "maße"
        widget: "object"
        summary: '{{fields.name}}: {{fields.schnitt}}'
        fields:
          - label: "Schnitt"
            name: "schnitt"
            widget: "number"
            value_type: "int"
            default: ""
          - label: "Maßeinheit"
            name: "maßeinheit"
            widget: "select"
            options:
            - { label: "Zentimeter", value: "cm" }
            - { label: "Millimeter", value: "mm" }
          
