site_url: https://makerwiki.netlify.app/
logo_url: https://makerwiki.netlify.app/icon.png

publish_mode: editorial_workflow
backend:
  name: git-gateway
  branch: main
  repo: thk-code-arch/makerwiki

media_folder: static/img
public_folder: /img

# Docs: https://www.netlifycms.org/docs/configuration-options/#collections
collections:
  - name: 'material'
    label: 'Material'
    # identifier_field: name
    folder: 'assets/content/material'
    create: true
    format: 'json'
    slug: '{{slug}}'
    # editor:
    #   preview: true
    fields:
      - { label: 'Material name', name: 'name', widget: 'string' }
      - { label: 'EN Material name', name: 'enName', widget: 'string' }
      - { label: 'FR Material name', name: 'frName', widget: 'string' }
      - { label: 'Short Description', name: 'shortDescription', widget: 'string' }
      - { label: 'MD Description', name: 'mdDescription', widget: 'markdown' }
      - {
          label: 'Material Image',
          name: 'image',
          widget: 'string',
          required: false
        }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
    # Process
  - name: 'process'
    label: 'Process'
    label_singular: 'process'
    folder: 'assets/content/process'
    create: true
    format: 'json'
    slug: '{{slug}}'
    preview_path: 'process/{{slug}}'
    fields:
      - { label: 'Process name', name: 'name', widget: 'string' }
      - { label: 'Alternative name', name: 'altName', widget: 'string' }
      - { label: 'Short Description', name: 'shortDescription', widget: 'string' }
      - { label: 'MD Description', name: 'mdDescription', widget: 'markdown' }
      - {
          label: 'Process Image',
          name: 'image',
          widget: 'string',
          required: false
        }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
